---
title: "Raw Data Tidy"
author: "Xun Wang"
date: "11/25/2019"
output: github_document
editor_options: 
  chunk_output_type: console
---

```{r setup, include=FALSE}
library(tidyverse)

knitr::opts_chunk$set(
	echo = TRUE,
	warning = FALSE,
	fig.width = 8, 
  fig.height = 6,
  out.width = "90%"
)

options(
  ggplot2.continuous.colour = "viridis",
  ggplot2.continuous.fill = "viridis"
)

scale_colour_discrete = scale_colour_viridis_d
scale_fill_discrete = scale_fill_viridis_d

theme_set(theme_minimal() + theme(legend.position = "bottom"))

set.seed(1)
```

#### Raw Data Explanation

*  **NYC Yellow Taxi Data:** The NYC yellow taxi raw data is from the  [TLC TriP Record Data](https://www1.nyc.gov/site/tlc/about/tlc-trip-record-data.page). It contains all the yellow taxi trip records in NYC from 2009 to 2019. First, to analyze change of the NYC yellow taxi use across 10 years, we focus on Yellow Taxi Trip Records raw data in every January of 2009, 2011, 2013, 2015, 2017, 2019. Next, to analyze change of the NYC yellow taxi use in detail, we focus on the yeat of 2018 and generate randomly sampled sub-datasets for each month in 2018. 

Because the raw data is too large, we put it in a folder named *raw_data* and added it to the `.gitignore` file. So the *raw_data* folder was not uploaded to the Github. The monthly sub-datasets were generated by randomly sampling 100,000 observations in each month of 2018 and saved in the folder *data*.

*  **NYC Weather Data:** The weather of NYC in 2018 raw data is from the [Global Historical Climatology Network's daily data (GHCND)](https://www.ncdc.noaa.gov/data-access/land-based-station-data/land-based-datasets/global-historical-climatology-network-ghcn).

This dataset can be downloaded by `rnoaa::meteo_pull_monitors`.






yellow_tripdata_2018_01 = 
  read_csv(file = "/Users/Kasza Lab/Desktop/yellow_tripdata_2018-01.csv") %>% 
  janitor::clean_names() %>% 
  sample_n(10000) %>% 
  arrange(tpep_pickup_datetime)

write.csv(yellow_tripdata_2018_01, "./tmp/yellow_tripdata_2018_01_sampled.csv", row.names = FALSE)

green_tripdata_2018_01 = 
  read_csv(file = "/Users/Kasza Lab/Desktop/green_tripdata_2018-01.csv") %>% 
  janitor::clean_names() %>% 
  sample_n(10000) %>% 
  arrange(lpep_pickup_datetime)

write.csv(green_tripdata_2018_01, "./tmp/green_tripdata_2018_01_sampled.csv", row.names = FALSE)

fhv_tripdata_2018_01 = 
  read_csv(file = "/Users/Kasza Lab/Desktop/fhv_tripdata_2018-01.csv") %>% 
  janitor::clean_names() %>% 
  sample_n(10000) %>% 
  arrange(pickup_date_time) %>% 
  view()

write.csv(fhv_tripdata_2018_01, "./tmp/fhv_tripdata_2018_01_sampled.csv", row.names = FALSE)

